// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// calc_slope_aspect
Rcpp::NumericVector calc_slope_aspect(arma::mat Rast, arma::mat EWkernel, double EWres, arma::mat NSkernel, double NSres, double smoothing);
RcppExport SEXP teamr_calc_slope_aspect(SEXP RastSEXP, SEXP EWkernelSEXP, SEXP EWresSEXP, SEXP NSkernelSEXP, SEXP NSresSEXP, SEXP smoothingSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< arma::mat >::type Rast(RastSEXP );
        Rcpp::traits::input_parameter< arma::mat >::type EWkernel(EWkernelSEXP );
        Rcpp::traits::input_parameter< double >::type EWres(EWresSEXP );
        Rcpp::traits::input_parameter< arma::mat >::type NSkernel(NSkernelSEXP );
        Rcpp::traits::input_parameter< double >::type NSres(NSresSEXP );
        Rcpp::traits::input_parameter< double >::type smoothing(smoothingSEXP );
        Rcpp::NumericVector __result = calc_slope_aspect(Rast, EWkernel, EWres, NSkernel, NSres, smoothing);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// calc_texture_full_image
arma::cube calc_texture_full_image(arma::mat rast, Rcpp::CharacterVector statistics, int n_grey, arma::vec window_dims, arma::vec shift);
RcppExport SEXP teamr_calc_texture_full_image(SEXP rastSEXP, SEXP statisticsSEXP, SEXP n_greySEXP, SEXP window_dimsSEXP, SEXP shiftSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< arma::mat >::type rast(rastSEXP );
        Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type statistics(statisticsSEXP );
        Rcpp::traits::input_parameter< int >::type n_grey(n_greySEXP );
        Rcpp::traits::input_parameter< arma::vec >::type window_dims(window_dimsSEXP );
        Rcpp::traits::input_parameter< arma::vec >::type shift(shiftSEXP );
        arma::cube __result = calc_texture_full_image(rast, statistics, n_grey, window_dims, shift);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
