# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculates slope and aspect using same formula as in the "landsat"
#' package by Sarah Goslee.
#'
#' This function is called by the \code{\link{slopeasp_par}} function. It is 
#' not intended to be used directly.
#'
#' @export
#' @param Rast a matrix of elevations. The slope and aspect will be calculated 
#' for the center pixel in the matrix.
#' @param EWkernel kernel to use for East-West gradient calculation
#' @param EWres East-West resolution
#' @param NSkernel kernel to use for North-South gradient calculation
#' @param NSres North-South resolution
#' @param smoothing positive integer for smoothing. 1 means no smoothing.
#' @return list with two elements. The first element is the calculated slope, 
#' the second element is the calculated aspect.
#' @references
#' Sarah Goslee. Analyzing Remote Sensing Data in {R}: The {landsat} Package.  
#' Journal of Statistical Software, 2011, 43:4, pg 1--25.  
#' http://www.jstatsoft.org/v43/i04/
calc_slope_aspect <- function(Rast, EWkernel, EWres, NSkernel, NSres, smoothing) {
    .Call('teamr_calc_slope_aspect', PACKAGE = 'teamr', Rast, EWkernel, EWres, NSkernel, NSres, smoothing)
}

#' Calculates a glcm texture for use in the glcm.R script
#'
#' This function is called by the \code{\link{glcm}} function. It is 
#' not intended to be used directly.
#'
#' @export
#' @param Rast a matrix containing the pixels to be used in the texture 
#' calculation
#' @param statistics a list of strings naming the texture statistics to 
#' calculate
#' @param base_indices a list of column-major indices giving the cells
#' included in the base image
#' @param offset_indices base_indices a list of column-major indices giving 
#' the cells ' included in the offset image
#' @param n_grey number of grey levels to use in texture calculation
#' @return a list of length equal to the length of the \code{statistics} input 
#' parameter, containing the selected textures measures
#' @references
#' Sarah Goslee. Analyzing Remote Sensing Data in {R}: The {landsat} Package.  
#' Journal of Statistical Software, 2011, 43:4, pg 1--25.  
#' http://www.jstatsoft.org/v43/i04/
calc_texture <- function(Rast, statistics, base_indices, offset_indices, n_grey) {
    .Call('teamr_calc_texture', PACKAGE = 'teamr', Rast, statistics, base_indices, offset_indices, n_grey)
}

