# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculates slope and aspect using the same formula as in the "landsat"
#' package by Sarah Goslee.
#' @export
calc_slope_aspect <- function(Rast, EWkernel, EWres, NSkernel, NSres, smoothing) {
    .Call('teamr_calc_slope_aspect', PACKAGE = 'teamr', Rast, EWkernel, EWres, NSkernel, NSres, smoothing)
}

#' Calculates a glcm texture for use in the glcm.R script
#' @export
calc_texture <- function(Rast, statistics, base_indices, offset_indices, n_grey) {
    .Call('teamr_calc_texture', PACKAGE = 'teamr', Rast, statistics, base_indices, offset_indices, n_grey)
}

