# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculates a glcm texture for use in the glcm.R script
#' @export
calc_texture <- function(rast, statistics, base_indices, offset_indices, n_grey) {
    .Call('teamr_calc_texture', PACKAGE = 'teamr', rast, statistics, base_indices, offset_indices, n_grey)
}

