#' Slope and aspect calculation in parallel for DEM \code{RasterLayer}
#'
#' This code calculate the slope and aspect for a DEM provided as a 
#' \code{RasterLayer}. The computations will be done in parallel if 
#' \code{sfQuickInit()} is called before \code{slopeasp_par}.
#'
#' The code for calculating the slope and aspect is taken directly from the 
#' \code{landsat} package by Sarah Goslee. See the help page for 
#' \code{slopeasp} in the \code{landsat} package for details on the parameters.
#'
#' @export
#' @import spatial.tools Rcpp RcppArmadillo
#' @param DEM DEM as \code{RasterLayer}
#' @param EWkernel kernel to use for East-West gradient calculation
#' @param NSkernel kernel to use for North-South gradient calculation
#' @param smoothing positive integer for smoothing. 1 means no smoothing.
#' @param filename output file for 2-band slope and aspect layer stack 
#' (optional)
#' @param ... additional parameters to pass to rasterEngine
#' @return RasterBrick with two layers: 'slope' and 'aspect'
#' @author Sarah Goslee and Alex Zvoleff
#' @references
#' Sarah Goslee. Analyzing Remote Sensing Data in {R}: The {landsat} Package.  
#' Journal of Statistical Software, 2011, 43:4, pg 1--25.  
#' http://www.jstatsoft.org/v43/i04/
#' @examples
#' #TODO: Write examples
slopeasp_par <- function(DEM, EWkernel, NSkernel, smoothing=1, filename=NULL, ...) {
    if (class(DEM) != 'RasterLayer') {
        stop('DEM must be a RasterLayer')
    }
    if (missing(EWkernel)) {
        EWkernel <- matrix(c(-1/8, 0, 1/8, -2/8, 0, 2/8, -1/8, 
            0, 1/8), ncol = 3, nrow = 3, byrow = TRUE)
    }
    if (missing(NSkernel)) {
        NSkernel <- matrix(c(1/8, 2/8, 1/8, 0, 0, 0, -1/8, -2/8, 
            -1/8), ncol = 3, nrow = 3, byrow = TRUE)
    }
    if (!identical(dim(NSkernel), dim(EWkernel))) {
        stop('NSkernel and EWkernel must have same dimensions')
    }
    # Make function to pass to rasterEngine for calculating slope and aspect.  
    # Result will be returned as a layer stack, with slope in band 1, aspect in 
    # band 2.
    # Add a wrapper for calc_slope_aspect function so that rasterEngine can 
    # pass ...  arguments to it (this avoids having to modify the 
    # auto-generated wrapper for the calc_slope_aspect R function that is 
    # generated by Rcpp).
    calc_slope_aspect_wrapper <- function(rast_wind, EWkernel, EWres, NSkernel, 
                                          NSres, smoothing, ...) {
        # Rast is a 3D array - convert it to 2D.
        calc_slope_aspect(rast_wind[, , 1], EWkernel, EWres, NSkernel, NSres, 
                          smoothing)
    }
    slopeasp_img <- rasterEngine(rast_wind=DEM, fun=calc_slope_aspect_wrapper,
                                 args=list(EWkernel=EWkernel, EWres=xres(DEM), 
                                           NSkernel=NSkernel, NSres=yres(DEM),
                                           smoothing=smoothing),
                                 window_dims=c(3, 3), filename=filename,
                                 outbands=2, ...)
    names(slopeasp_img) <- c('slope', 'aspect')
    setMinMax(slopeasp_img)
    return(slopeasp_img)
}
